# Generated by Django 5.0.14 on 2025-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la catégorie (ex: Agriculture & Élevage)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la catégorie', max_length=500, null=True)),
                ('icone', models.CharField(blank=True, help_text="Code emoji ou classe CSS pour l'icône (ex: 🌾, fa-seedling)", max_length=50, null=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans les listes (0 = premier)")),
                ('est_active', models.BooleanField(default=True, help_text='Catégorie visible et utilisable')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
    ]
