# Generated by Django 5.0.1 on 2025-11-05 11:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('montant_objectif', models.DecimalField(decimal_places=2, help_text='Montant total à collecter (en FCFA).', max_digits=12)),
                ('montant_actuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant déjà collecté.', max_digits=12)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('termine', 'Terminé')], default='brouillon', max_length=20)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('porteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_projets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
