<<<<<<< HEAD
# Generated by Django 5.0.1 on 2025-11-05 11:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
=======
# Generated by Django 5.0.14 on 2025-11-06 12:48

>>>>>>> ancienne_version
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> ancienne_version
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('montant_objectif', models.DecimalField(decimal_places=2, help_text='Montant total à collecter (en FCFA).', max_digits=12)),
                ('montant_actuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant déjà collecté.', max_digits=12)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('termine', 'Terminé')], default='brouillon', max_length=20)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('porteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_projets', to=settings.AUTH_USER_MODEL)),
            ],
=======
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la catégorie (ex: Agriculture & Élevage)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la catégorie', max_length=500, null=True)),
                ('icone', models.CharField(blank=True, help_text="Code emoji ou classe CSS pour l'icône (ex: 🌾, fa-seedling)", max_length=50, null=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans les listes (0 = premier)")),
                ('est_active', models.BooleanField(default=True, help_text='Catégorie visible et utilisable')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre_affichage', 'nom'],
            },
>>>>>>> ancienne_version
        ),
    ]
