# Generated by Django 5.0.14 on 2025-11-06 13:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre accrocheur du projet', max_length=200)),
                ('description_courte', models.TextField(help_text='Résumé en quelques lignes', max_length=300)),
                ('description_complete', models.TextField(help_text='Description détaillée du projet')),
                ('region', models.CharField(choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('saint-louis', 'Saint-Louis'), ('diourbel', 'Diourbel'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('kaolack', 'Kaolack'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('tambacounda', 'Tambacounda'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou'), ('ziguinchor', 'Ziguinchor')], help_text='Région de réalisation du projet', max_length=20)),
                ('ville', models.CharField(help_text='Ville ou commune de réalisation', max_length=100)),
                ('montant_objectif', models.DecimalField(decimal_places=0, help_text='Montant à collecter en FCFA (100k à 10M)', max_digits=12, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(10000000)])),
                ('montant_collecte', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Montant actuellement collecté', max_digits=12)),
                ('nombre_contributeurs', models.PositiveIntegerField(default=0, help_text='Nombre de personnes ayant contribué')),
                ('type_financement', models.CharField(blank=True, choices=[('tout_ou_rien', 'Tout ou rien (100%)'), ('flexible_50', 'Flexible 50% minimum'), ('solidaire', 'Solidaire (0% minimum)')], help_text="Type défini par l'administrateur lors de la validation", max_length=20, null=True)),
                ('commentaire_admin_financement', models.TextField(blank=True, help_text="Commentaire de l'admin sur le choix du type de financement", null=True)),
                ('duree_campagne_jours', models.PositiveIntegerField(help_text='Durée de la campagne en jours (7 à 90)', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(90)])),
                ('date_soumission', models.DateTimeField(blank=True, help_text='Date de soumission pour validation', null=True)),
                ('date_validation', models.DateTimeField(blank=True, help_text="Date de validation par l'admin", null=True)),
                ('date_debut_campagne', models.DateTimeField(blank=True, help_text='Date de début de la campagne', null=True)),
                ('date_fin_campagne', models.DateTimeField(blank=True, help_text='Date de fin de la campagne', null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('rejete', 'Rejeté'), ('actif', 'Campagne active'), ('finance', 'Financé avec succès'), ('non_finance', 'Non financé'), ('suspendu', 'Suspendu'), ('archive', 'Archivé')], default='brouillon', help_text='Statut actuel du projet', max_length=20)),
                ('motif_rejet', models.TextField(blank=True, help_text="Motif de rejet par l'administrateur", null=True)),
                ('image_principale', models.ImageField(blank=True, help_text='Image principale du projet', null=True, upload_to='projects/')),
                ('video_url', models.URLField(blank=True, help_text='URL de la vidéo de présentation (YouTube, Vimeo)', null=True)),
                ('document_budget', models.FileField(blank=True, help_text='Document de budget prévisionnel', null=True, upload_to='projects/documents/')),
                ('document_business_plan', models.FileField(blank=True, help_text='Business plan ou note de présentation', null=True, upload_to='projects/documents/')),
                ('nombre_vues', models.PositiveIntegerField(default=0, help_text='Nombre de consultations du projet')),
                ('nombre_partages', models.PositiveIntegerField(default=0, help_text='Nombre de partages sur réseaux sociaux')),
                ('fonds_debloques', models.BooleanField(default=False, help_text='Fonds débloqués au porteur de projet')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(help_text='Catégorie du projet', on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='projects.categorie')),
                ('porteur', models.ForeignKey(help_text='Utilisateur qui a créé le projet', on_delete=django.db.models.deletion.CASCADE, related_name='projets_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
    ]
