# Generated by Django 5.0.1 on 2025-11-05 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, max_length=100, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to='projects.categorie'),
        ),
    ]
