# Generated by Django 5.0.14 on 2025-11-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('infos_demandees', 'Informations demandées')], help_text="Décision prise par l'administrateur", max_length=20)),
                ('type_financement_choisi', models.CharField(blank=True, choices=[('tout_ou_rien', 'Tout ou rien (100%)'), ('flexible_50', 'Flexible 50% minimum'), ('solidaire', 'Solidaire (0% minimum)')], help_text='Type de financement choisi si approuvé', max_length=20, null=True)),
                ('commentaire', models.TextField(help_text="Commentaire de l'administrateur")),
                ('motif_rejet', models.TextField(blank=True, help_text='Motifs détaillés en cas de rejet', null=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('administrateur', models.ForeignKey(help_text='Administrateur qui a pris la décision', on_delete=django.db.models.deletion.CASCADE, related_name='validations_effectuees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(help_text='Projet concerné par la validation', on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='projects.projet')),
            ],
            options={
                'verbose_name': 'Validation de projet',
                'verbose_name_plural': 'Validations de projets',
                'ordering': ['-date_validation'],
            },
        ),
    ]
