# Generated by Django 5.0.14 on 2025-11-06 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_validationprojet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiseAJourProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la mise à jour', max_length=200)),
                ('contenu', models.TextField(help_text='Contenu détaillé de la mise à jour')),
                ('images', models.ImageField(blank=True, help_text='Images illustrant la mise à jour', null=True, upload_to='mises_a_jour/')),
                ('visibilite', models.CharField(choices=[('public', 'Public (visible par tous)'), ('contributeurs', 'Contributeurs uniquement')], default='public', help_text='Qui peut voir cette mise à jour', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(help_text='Auteur de la mise à jour (normalement le porteur)', on_delete=django.db.models.deletion.CASCADE, related_name='mises_a_jour_publiees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(help_text='Projet concerné par la mise à jour', on_delete=django.db.models.deletion.CASCADE, related_name='mises_a_jour', to='projects.projet')),
            ],
            options={
                'verbose_name': 'Mise à jour de projet',
                'verbose_name_plural': 'Mises à jour de projets',
                'ordering': ['-date_publication'],
            },
        ),
    ]
