# Generated by Django 5.0.14 on 2025-12-11 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_miseajourprojet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['statut', '-date_creation'], name='projet_statut_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['region', 'categorie'], name='projet_region_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['porteur', 'statut'], name='projet_porteur_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['categorie', 'statut'], name='projet_cat_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['-date_debut_campagne'], name='projet_debut_camp_idx'),
        ),
    ]
