# Generated by Django 5.0.14 on 2025-12-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projet_projet_statut_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('modification_demandee', 'Modification demandée'), ('rejete', 'Rejeté'), ('actif', 'Campagne active'), ('finance', 'Financé avec succès'), ('non_finance', 'Non financé'), ('suspendu', 'Suspendu'), ('archive', 'Archivé')], default='brouillon', help_text='Statut actuel du projet', max_length=25),
        ),
    ]
