# Generated by Django 5.0.14 on 2025-11-06 13:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_validationprojet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, help_text='Montant de la contribution en FCFA (min 1000)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1000'))])),
                ('message_soutien', models.TextField(blank=True, help_text='Message optionnel de soutien au porteur', max_length=500, null=True)),
                ('est_anonyme', models.BooleanField(default=False, help_text='Contribution anonyme (nom masqué publiquement)')),
                ('reference_paiement', models.CharField(help_text='Référence unique de la transaction', max_length=100, unique=True)),
                ('moyen_paiement', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money')], help_text='Moyen de paiement choisi', max_length=20)),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échec'), ('rembourse', 'Remboursé')], default='en_attente', help_text='Statut de la transaction', max_length=20)),
                ('recu_pdf', models.FileField(blank=True, help_text='Reçu PDF généré automatiquement', null=True, upload_to='recus/')),
                ('date_contribution', models.DateTimeField(auto_now_add=True)),
                ('date_remboursement', models.DateTimeField(blank=True, help_text='Date de remboursement si applicable', null=True)),
                ('donnees_paiement', models.JSONField(blank=True, default=dict, help_text='Données techniques de simulation du paiement')),
                ('contributeur', models.ForeignKey(help_text='Utilisateur qui contribue', on_delete=django.db.models.deletion.CASCADE, related_name='contributions_effectuees', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(help_text='Projet soutenu', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='projects.projet')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-date_contribution'],
            },
        ),
    ]
