# Generated by Django 5.0.14 on 2025-12-11 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('projects', '0005_projet_projet_statut_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['projet', 'statut_paiement'], name='contrib_projet_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['contributeur', '-date_contribution'], name='contrib_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['statut_paiement', '-date_contribution'], name='contrib_statut_date_idx'),
        ),
    ]
