# Generated by Django 5.0.14 on 2025-11-06 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_validationprojet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(help_text='Contenu du commentaire', max_length=1000)),
                ('est_signale', models.BooleanField(default=False, help_text="Commentaire signalé par d'autres utilisateurs")),
                ('nombre_signalements', models.PositiveIntegerField(default=0, help_text='Nombre total de signalements')),
                ('est_masque', models.BooleanField(default=False, help_text='Commentaire masqué par un modérateur')),
                ('raison_masquage', models.CharField(blank=True, help_text='Raison du masquage', max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(help_text='Utilisateur qui a écrit le commentaire', on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_ecrits', to=settings.AUTH_USER_MODEL)),
                ('commentaire_parent', models.ForeignKey(blank=True, help_text='Commentaire parent (pour les réponses)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='interactions.commentaire')),
                ('projet', models.ForeignKey(help_text='Projet commenté', on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='projects.projet')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Partage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('lien_copie', 'Lien copié')], help_text='Plateforme de partage', max_length=20)),
                ('date_partage', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(help_text='Projet partagé', on_delete=django.db.models.deletion.CASCADE, related_name='partages', to='projects.projet')),
                ('utilisateur', models.ForeignKey(blank=True, help_text='Utilisateur qui partage (peut être anonyme)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partages_effectues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partage',
                'verbose_name_plural': 'Partages',
                'ordering': ['-date_partage'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(help_text='Projet mis en favori', on_delete=django.db.models.deletion.CASCADE, related_name='mis_en_favoris', to='projects.projet')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur qui met en favori', on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'projet')},
            },
        ),
    ]
