# Generated by Django 5.0.14 on 2025-11-06 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_signalement', models.CharField(choices=[('projet', 'Projet'), ('commentaire', 'Commentaire'), ('utilisateur', 'Utilisateur')], help_text="Type d'élément signalé", max_length=20)),
                ('objet_signale_id', models.PositiveIntegerField(help_text="ID de l'objet signalé (projet, commentaire, utilisateur)")),
                ('motif', models.CharField(choices=[('fraude', 'Fraude ou escroquerie'), ('contenu_inapproprie', 'Contenu inapproprié'), ('informations_fausses', 'Informations fausses'), ('spam', 'Spam ou contenu commercial non sollicité'), ('violation_droits', "Violation de droits d'auteur"), ('incitation_haine', 'Incitation à la haine'), ('autre', 'Autre (préciser en description)')], help_text='Motif du signalement', max_length=30)),
                ('description', models.TextField(help_text='Description détaillée du signalement', max_length=1000)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('rejete', 'Rejeté (non fondé)')], default='nouveau', help_text='Statut du traitement', max_length=20)),
                ('decision_admin', models.TextField(blank=True, help_text="Décision et commentaires de l'administrateur", null=True)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Date de traitement par un admin', null=True)),
                ('auteur', models.ForeignKey(help_text='Utilisateur qui effectue le signalement', on_delete=django.db.models.deletion.CASCADE, related_name='signalements_effectues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
                'unique_together': {('auteur', 'type_signalement', 'objet_signale_id')},
            },
        ),
    ]
