# Generated by Django 5.0.14 on 2025-12-11 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_signalement'),
        ('projects', '0005_projet_projet_statut_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commentaire',
            index=models.Index(fields=['projet', 'date_creation'], name='comment_projet_date_idx'),
        ),
        migrations.AddIndex(
            model_name='commentaire',
            index=models.Index(fields=['auteur', '-date_creation'], name='comment_auteur_date_idx'),
        ),
        migrations.AddIndex(
            model_name='commentaire',
            index=models.Index(fields=['est_signale', 'est_masque'], name='comment_moderation_idx'),
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['statut', '-date_signalement'], name='signal_statut_date_idx'),
        ),
        migrations.AddIndex(
            model_name='signalement',
            index=models.Index(fields=['type_signalement', 'objet_signale_id'], name='signal_type_obj_idx'),
        ),
    ]
