<<<<<<< HEAD
# Generated by Django 5.0.1 on 2025-11-04 16:48

import apps.users.models
=======
# Generated by Django 5.0.14 on 2025-11-06 11:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
>>>>>>> ancienne_version
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Utilisateur',
=======
            name='User',
>>>>>>> ancienne_version
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
<<<<<<< HEAD
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
=======
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, help_text='Format: +221xxxxxxxxx ou xxxxxxxxx', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format sénégalais.', regex='^\\+221[0-9]{9}$|^[0-9]{9}$')])),
                ('type_utilisateur', models.CharField(choices=[('contributeur', 'Contributeur'), ('porteur', 'Porteur de projet'), ('admin', 'Administrateur')], default='contributeur', help_text='Type de compte utilisateur', max_length=20)),
                ('photo_profil', models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='profiles/')),
                ('biographie', models.TextField(blank=True, help_text="Courte biographie de l'utilisateur", max_length=500, null=True)),
                ('region', models.CharField(blank=True, choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('saint-louis', 'Saint-Louis'), ('diourbel', 'Diourbel'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('kaolack', 'Kaolack'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('tambacounda', 'Tambacounda'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('sedhiou', 'Sédhiou'), ('ziguinchor', 'Ziguinchor')], help_text='Région de résidence', max_length=20, null=True)),
                ('ville', models.CharField(blank=True, help_text='Ville ou commune de résidence', max_length=100, null=True)),
                ('date_derniere_connexion', models.DateTimeField(blank=True, help_text='Date et heure de la dernière connexion', null=True)),
                ('statut_compte', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('supprime', 'Supprimé')], default='actif', help_text='Statut du compte utilisateur', max_length=20)),
>>>>>>> ancienne_version
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
<<<<<<< HEAD
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.users.models.UtilisateurManager()),
=======
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
>>>>>>> ancienne_version
            ],
        ),
    ]
