# Generated by Django 5.0.14 on 2025-11-06 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('projet_valide', 'Projet validé'), ('projet_rejete', 'Projet rejeté'), ('nouvelle_contribution', 'Nouvelle contribution reçue'), ('commentaire_projet', 'Nouveau commentaire sur votre projet'), ('objectif_atteint', 'Objectif de financement atteint'), ('fin_campagne', 'Fin de campagne'), ('contribution_confirmee', 'Contribution confirmée'), ('mise_a_jour_projet', 'Mise à jour de projet suivi'), ('projet_finance', 'Projet soutenu financé'), ('favori_nouveau_projet', 'Nouveau projet dans catégorie favorite'), ('rappel_projet', 'Rappel projet bientôt terminé'), ('bienvenue', 'Bienvenue sur DiapalSen')], help_text='Type de notification', max_length=30)),
                ('titre', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('contenu', models.TextField(help_text='Contenu détaillé de la notification', max_length=500)),
                ('lien_action', models.CharField(blank=True, help_text="Lien vers l'élément concerné (projet, contribution, etc.)", max_length=200, null=True)),
                ('est_lue', models.BooleanField(default=False, help_text="Notification lue par l'utilisateur")),
                ('date_lecture', models.DateTimeField(blank=True, help_text='Date de lecture de la notification', null=True)),
                ('est_envoyee_email', models.BooleanField(default=False, help_text='Notification envoyée par email')),
                ('donnees_contextuelles', models.JSONField(blank=True, default=dict, help_text='Données additionnelles (ID projet, montant, etc.)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(help_text='Utilisateur qui reçoit la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
