# Generated by Django 5.0.14 on 2025-12-11 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'est_lue', '-date_creation'], name='notif_user_lue_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification', '-date_creation'], name='notif_type_date_idx'),
        ),
    ]
