# Generated by Django 5.0.14 on 2025-12-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notif_user_lue_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('projet_valide', 'Projet validé'), ('projet_rejete', 'Projet rejeté'), ('infos_demandees', 'Modification demandée'), ('nouvelle_contribution', 'Nouvelle contribution reçue'), ('commentaire_projet', 'Nouveau commentaire sur votre projet'), ('objectif_atteint', 'Objectif de financement atteint'), ('fin_campagne', 'Fin de campagne'), ('contribution_confirmee', 'Contribution confirmée'), ('mise_a_jour_projet', 'Mise à jour de projet suivi'), ('projet_finance', 'Projet soutenu financé'), ('favori_nouveau_projet', 'Nouveau projet dans catégorie favorite'), ('rappel_projet', 'Rappel projet bientôt terminé'), ('bienvenue', 'Bienvenue sur DiapalSen')], help_text='Type de notification', max_length=30),
        ),
    ]
